version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "OCR-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1g22i2cs7ttso"
s3_prefix = "OCR-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
